AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Backup Demo - Database Resources (RDS)'

Parameters:
  EnvironmentName:
    Description: Environment name prefix for resources
    Type: String
    
  DBPassword:
    Description: RDS database password
    Type: String
    NoEcho: true
    
  VpcId:
    Description: VPC ID
    Type: String
    
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Type: String
    
  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Type: String

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-RDS-SG
        - Key: BackupDemo
          Value: true

  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      Tags:
        - Key: BackupDemo
          Value: true

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-mysql
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      MultiAZ: false
      Tags:
        - Key: BackupDemo
          Value: true

Outputs:
  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}-RDSEndpoint