AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Backup Demo - Storage Resources (S3 and DynamoDB)'

Parameters:
  EnvironmentName:
    Description: Environment name prefix for resources
    Type: String

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-demo-bucket-${AWS::AccountId}
      Tags:
        - Key: BackupDemo
          Value: true

  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${EnvironmentName}-DemoTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: BackupDemo
          Value: true

Outputs:
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref DemoBucket
    Export:
      Name: !Sub ${EnvironmentName}-S3BucketName

  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref DemoTable
    Export:
      Name: !Sub ${EnvironmentName}-DynamoDBTableName